# Logistic Regression

## Importing the libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [4]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
dataset

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0               1000025                5                        1   
1               1002945                5                        4   
2               1015425                3                        1   
3               1016277                6                        8   
4               1017023                4                        1   
..                  ...              ...                      ...   
678              776715                3                        1   
679              841769                2                        1   
680              888820                5                       10   
681              897471                4                        8   
682              897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                           1                  1                            2   
1                           4                  5                            7   
2                           1                  1                            2   
3                           8                  1                            3   
4                           1                  3                            2   
..                        ...                ...                          ...   
678                         1                  1                            3   
679                         1                  1                            2   
680                        10                  3                            7   
681                         6                  4                            3   
682                         8                  5                            4   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0              1                3                1        1      2  
1             10                3                2        1      2  
2              2                3                1        1      2  
3              4                3                7        1      2  
4              1                3                1        1      2  
..           ...              ...              ...      ...    ...  
678            2                1                1        1      2  
679            1                1                1        1      2  
680            3                8               10        2      4  
681            4               10                6        1      4  
682            5               10                4        1      4  

[683 rows x 11 columns]

In [6]:
dataset["Class"].value_counts()

2    444
4    239
Name: Class, dtype: int64

In [9]:
dataset.shape

(683, 11)

In [8]:
X.shape

(683, 10)

In [10]:
y.shape

(683,)

## Splitting the dataset into the Training set and Test set

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
X_train

array([[ 142932,       7,       6, ...,       9,      10,       2],
       [1120559,       8,       3, ...,       8,       9,       8],
       [1254538,       8,      10, ...,      10,      10,       1],
       ...,
       [1214092,       1,       1, ...,       1,       1,       1],
       [1303489,       3,       1, ...,       2,       1,       1],
       [ 378275,      10,       9, ...,       7,       7,       1]],
      dtype=int64)

## Feature Scaling

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train.shape
X_test.shape
X_train

array([[-1.38219432,  0.91903747,  0.9407658 , ...,  2.22576767,
         2.27129602,  0.24623928],
       [ 0.03390689,  1.27578287, -0.04290763, ...,  1.82407819,
         1.94996317,  3.74830911],
       [ 0.22797663,  1.27578287,  2.25233038, ...,  2.62745714,
         2.27129602, -0.33743902],
       ...,
       [ 0.16939025, -1.22143494, -0.69868992, ..., -0.98774815,
        -0.62069958, -0.33743902],
       [ 0.29888258, -0.50794414, -0.69868992, ..., -0.58605867,
        -0.62069958, -0.33743902],
       [-1.04129794,  1.98927367,  1.92443923, ...,  1.42238871,
         1.30729749, -0.33743902]])

## Training the Logistic Regression model on the Training set

In [18]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Making the Confusion Matrix

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)*100

[[103   4]
 [  5  59]]


94.73684210526315

In [21]:
X_test.shape

(171, 10)

In [24]:
X_train[8]

array([ 0.13005455, -0.86468954, -0.69868992, -0.06218591, -0.28415674,
       -0.5465486 , -0.68084439, -0.58605867, -0.62069958, -0.33743902])

In [25]:
y_train[8]

2

In [27]:
classifier.predict([X_train[8]])

array([2], dtype=int64)