# Title
## Heading2
### Heading 3
#### Heading4
##### Heading5
###### heading 6

**Bold**
*Italic*

- To run the cell: Alt + Enter or Shift + Enter

### Python Libraries
- NumPy
- Pandas
- Matplotlib
- Seaborn
- Sklearn

### NumPy Library
- Installation: **"pip install numpy" or "conda install numpy"**
- Importing:  **import numpy**

In [1]:
import numpy as np

In [2]:
## Version
np.__version__

'1.16.4'

In [4]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [5]:
## 1-Dimentional array
n1 = np.array([1,2,3.5,'string'])
n1

array(['1', '2', '3.5', 'string'], dtype='<U32')

In [7]:
print(n1.ndim) # to check n-dimentions
print(type(n1))

1
<class 'numpy.ndarray'>


In [12]:
## 2-D array
### np.array([ [row1],[row2] ])
n2 = np.array([[1,2,3,4],[5,6,7,8]])
print(n2)
print('Rows & columns : ',n2.shape)
print('N-Dimentions : ',n2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
Rows & columns :  (2, 4)
N-Dimentions :  2


In [17]:
## 3-D array
n3 = np.array([[ [1,2,3],[3,2,1] ]])
# print(n3)
# print(n3.ndim)

n33 = np.array([ [[1,2,3,4],[5,6,7,8]], [[11,12,13,14],[15,16,17,18]] ])
print(n33)
print(n33.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [15 16 17 18]]]
3


#### Why numpy when we have List?

In [18]:
list1 = [1,2,3,4]
list1 + 10

TypeError: can only concatenate list (not "int") to list

In [22]:
np1 = np.array([1,2,3,4])
np1 + 10

array([11, 12, 13, 14])

In [24]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [25]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [26]:
## np.linspace(start, stop, len of values)
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [27]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [28]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

#### Reshape
- Giving a new shape to an array
- The product of rows and columns in the new array should equal to toal no.of elements.

In [30]:
a = np.array([[1,2,3,4,5],[10,20,30,40,50]])
print(a)
print(a.shape)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
(2, 5)


In [31]:
## Possible ways to reshape
### 2 * 5 = 10
### 5 * 2 = 10
### 10 * 1


In [35]:
print(a.reshape(5,2))
print(a.reshape(5,2).shape)

[[ 1  2]
 [ 3  4]
 [ 5 10]
 [20 30]
 [40 50]]
(5, 2)


In [36]:
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

- Try to do more examples on reshape in help()

### Statistical operations

In [38]:
a1 = np.arange(10,30)
a1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [39]:
len(a1)

20

In [40]:
a2 = a1.reshape(4,5)
a2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [44]:
print(np.max(a1))
print(np.min(a1))
print(np.argmax(a1))## Returns index of max value
print(np.argmin(a1))## Returns index of min value

29
10
19
0


In [48]:
print(np.mean(a1))
print(np.var(a1))
print(np.std(a1))

19.5
33.25
5.766281297335398


In [51]:
print(np.exp(10))
print(np.log2(10))

22026.465794806718
3.321928094887362


In [55]:
print(np.sin(3.14/6))
print(np.cos(3.14/3))
print(np.tan(3.14/4))

0.4997701026431024
0.5004596890082058
0.9992039901050427
